<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log Out</name>
   <tag></tag>
   <elementGuidId>10fba4a9-b2f1-4e26-b5f4-31379a32be2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.profile-link-label.logout.uiOutputURL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content_30:2928;a']/div/div[2]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c69823ae-8f66-44b6-9cde-acaf498a5b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/secur/logout.jsp</value>
      <webElementGuid>a564ac51-38c3-4d9c-8229-eed19f3c49d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>5658b3ee-65cf-46a4-b22a-17a1543a22ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-link-label logout uiOutputURL</value>
      <webElementGuid>46eff19a-0eec-4167-9d9e-afe22e66f1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>27:3068;a</value>
      <webElementGuid>f63c2085-92b3-4d8a-a0f4-1da724b7706e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>uiOutputURL</value>
      <webElementGuid>cc6529ae-215b-48e5-9e95-4446ea63a029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interactive-lib-uid</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>294db500-260e-4e2e-a4a2-a19b2ffd0503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log Out</value>
      <webElementGuid>eb2f160f-f93f-4a10-9f2c-f54ce885c452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content_30:2928;a&quot;)/div[@class=&quot;oneUserProfileCard&quot;]/div[@class=&quot;profile-card-indent&quot;]/div[@class=&quot;profile-card-toplinks&quot;]/a[@class=&quot;profile-link-label logout uiOutputURL&quot;]</value>
      <webElementGuid>7aa3ef5f-ca05-4153-98cd-3bc12beea9aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_30:2928;a']/div/div[2]/div/a[2]</value>
      <webElementGuid>d6676777-c78f-4ca5-a92d-1590f00ebc56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log Out')]</value>
      <webElementGuid>f0dc904c-5edb-47a6-b72f-c8918cdd333e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[2]/following::a[1]</value>
      <webElementGuid>40ef34aa-84db-4b8a-98d8-b07f0e398c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mindful-badger-r5gt64-dev-ed.trailblaze.my.salesforce.com'])[1]/following::a[2]</value>
      <webElementGuid>5c1a60b8-8b51-4735-bcd9-922212729ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/preceding::a[1]</value>
      <webElementGuid>3e26c37b-1508-4e40-8d88-faf3f30c2b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display Density'])[1]/preceding::a[1]</value>
      <webElementGuid>0258352b-5490-4aac-ae4d-2f87852248c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log Out']/parent::*</value>
      <webElementGuid>51314679-f0c4-46c6-b29f-a3779a3b3530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/secur/logout.jsp')]</value>
      <webElementGuid>4d62032a-4751-4743-ba89-0218af07a517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a[2]</value>
      <webElementGuid>eebb6d51-6ae5-4e92-ad02-32a522291c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/secur/logout.jsp' and (text() = 'Log Out' or . = 'Log Out')]</value>
      <webElementGuid>91bd446d-1f79-4159-84ca-8609fd5dc989</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
