<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View profile_slds-icon-waffle</name>
   <tag></tag>
   <elementGuidId>33a7bcf1-8e7f-4375-b4d3-f7a91b960fc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.slds-icon-waffle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='457:83;a']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>86306fd6-1413-426d-8c1f-02cc4751e936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-icon-waffle</value>
      <webElementGuid>eccc06a8-993f-4c93-9045-ce3ffa39d908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>440:83;a</value>
      <webElementGuid>90da6b9d-090d-4a33-bc12-85a82a44a7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;457:83;a&quot;)/div[@class=&quot;slds-icon-waffle&quot;]</value>
      <webElementGuid>44eaf4f5-39ca-4db6-9b32-c147310a74ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='457:83;a']/div</value>
      <webElementGuid>e39592b0-1854-49e2-9b52-c45a67470c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View profile'])[1]/following::div[10]</value>
      <webElementGuid>c387b24a-800b-4d8a-b080-4c9de5ffe756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/following::div[13]</value>
      <webElementGuid>f15dc83e-dc35-47f9-a763-628312ac3e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App Launcher'])[1]/preceding::div[10]</value>
      <webElementGuid>a48db378-743c-4ef1-aa9d-21def4fff198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setup'])[4]/preceding::div[10]</value>
      <webElementGuid>d1ef0999-4f21-4781-8562-0e734a0bb1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button/div/div</value>
      <webElementGuid>44b045f8-77ac-4327-847b-d45deff0ec2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
