<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sales (1)</name>
   <tag></tag>
   <elementGuidId>c5507af2-fadd-413f-b2b6-359f40019279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#07pGC000000RdLEYA0 > div.slds-size_small</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='07pGC000000RdLEYA0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ebdd2a1-9b36-47db-b8e1-b1b329ea6011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-size_small</value>
      <webElementGuid>13359522-82d3-4e23-99e9-19902261f389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sales</value>
      <webElementGuid>fc6bd589-eb77-4007-942d-2c935cc9f09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;07pGC000000RdLEYA0&quot;)/div[@class=&quot;slds-size_small&quot;]</value>
      <webElementGuid>57c4ecc5-26b5-4a24-ab18-d3489d49fd70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='07pGC000000RdLEYA0']/div</value>
      <webElementGuid>61924f4d-f015-422d-94bf-60df653c7f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps'])[2]/following::div[8]</value>
      <webElementGuid>7c645551-9f1f-4996-a429-59fe70367058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search apps and items...'])[1]/following::div[10]</value>
      <webElementGuid>9a65c66d-36da-4e25-854f-a5554428c23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/preceding::div[1]</value>
      <webElementGuid>1d289666-c9d8-48f1-a805-a224f11c7ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/preceding::div[4]</value>
      <webElementGuid>5aacd063-7a1c-45bc-b6fc-c80f00adcc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//one-app-launcher-menu-item[7]/a/div</value>
      <webElementGuid>f32b792e-bd23-4180-9e7d-abd0d9398a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sales' or . = 'Sales')]</value>
      <webElementGuid>cc81014b-05b1-4290-8499-f5b901dd0824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
