<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Sales</name>
   <tag></tag>
   <elementGuidId>7e390df6-f117-42f7-a4b5-d4082a7ed380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#07pGC000000RdLEYA0 > div.slds-size_small > lightning-formatted-rich-text.al-menu-item-label.slds-truncate.slds-rich-text-editor__output > span > p.slds-truncate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='07pGC000000RdLEYA0']/div/lightning-formatted-rich-text/span/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>43ac28de-7382-45db-ae59-3f4c5f02cef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-truncate</value>
      <webElementGuid>8df0b1a7-3c81-4cf8-a662-222e6c7a7fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sales</value>
      <webElementGuid>162ff156-41ea-4032-8089-c9a8491bdedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;07pGC000000RdLEYA0&quot;)/div[@class=&quot;slds-size_small&quot;]/lightning-formatted-rich-text[@class=&quot;al-menu-item-label slds-truncate slds-rich-text-editor__output&quot;]/span[1]/p[@class=&quot;slds-truncate&quot;]</value>
      <webElementGuid>9638a1fa-515e-42e7-b580-c433310d57b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='07pGC000000RdLEYA0']/div/lightning-formatted-rich-text/span/p</value>
      <webElementGuid>98236d77-3e55-405b-a2a3-e4fad696d54d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps'])[2]/following::p[7]</value>
      <webElementGuid>93ae33d0-7637-4d2c-a2b6-6b50bd49e42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search apps and items...'])[1]/following::p[7]</value>
      <webElementGuid>6e54a48b-af30-419f-b0b4-f91c35840071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/preceding::p[1]</value>
      <webElementGuid>35805e6f-e192-4cf0-bdca-501bd3e710b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/preceding::p[1]</value>
      <webElementGuid>79d6cc93-edf8-407a-a648-e537734ba990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sales']/parent::*</value>
      <webElementGuid>79da94f3-6f9b-46c6-b0e0-9a2c388879eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//one-app-launcher-menu-item[7]/a/div/lightning-formatted-rich-text/span/p</value>
      <webElementGuid>c8b9dc7a-4b88-4ac9-b0a5-00e64c2295fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Sales' or . = 'Sales')]</value>
      <webElementGuid>4515e61f-0de7-49aa-9ac3-c1f8aef7b770</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
