<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__MasterLabel</name>
   <tag></tag>
   <elementGuidId>38b16180-f458-465f-bb6c-05f293bc4d6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MasterLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MasterLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>844741a1-5a7a-46a8-8677-6ba42681df9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MasterLabel</value>
      <webElementGuid>19a675e9-4974-4128-900b-cf90bc3714b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>4ad22d34-75e9-439b-bf5a-0d13622a99cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MasterLabel</value>
      <webElementGuid>ea3c4afe-4890-4156-98e8-0d5b4df529e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>DeveloperNameInputElement.setName(this, document.getElementById('DeveloperName'), 'CustomObject1');</value>
      <webElementGuid>3d7ed40a-cdc3-4850-b469-c68637b543eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CustomEntityDefinition.setNameLabel(this, document.getElementById('MasterNameFieldLabel'));</value>
      <webElementGuid>c59c3a69-2c9a-42a5-9274-4ad74d8da594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>889bc31b-d6a6-43b7-9501-26911e9f2bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>dad3ab31-ac83-449c-981d-faac3bdd5a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>59024915-a191-4bf7-be67-3f86bf3102ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MasterLabel&quot;)</value>
      <webElementGuid>fc4bbb1f-794b-4276-b575-87c3db36bdd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_New Custom Object  Salesforce/iframe_New Custom Object_vfFrameId_1703668097612</value>
      <webElementGuid>9fde9464-c460-4977-ac4f-dfbe66391729</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MasterLabel']</value>
      <webElementGuid>7a8d1f8c-0da9-4675-852a-5221aaa73657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ep']/div[2]/div[3]/table/tbody/tr[2]/td[2]/div/input</value>
      <webElementGuid>ddcec2d5-816d-4fa5-b6bb-53c56b8007f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>51d69619-d6a3-45d3-ada4-9b22739b914c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MasterLabel' and @name = 'MasterLabel' and @type = 'text']</value>
      <webElementGuid>62fbccda-6460-4050-a578-a512d979dc1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
