<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Launch New Custom Tab Wizard after sa_5174e9</name>
   <tag></tag>
   <elementGuidId>4fc9e307-758d-4f38-891f-49356fd27db2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='save'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bottomButtonRow > input[name=&quot;save&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e93a4df-58b9-4da7-b5f0-bbfc2bb7e339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value> Save </value>
      <webElementGuid>f5444d26-65e0-4ad9-b2fb-041c1f8e4cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>0642c3d1-1e71-4fd5-bc75-ea65198c39c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>2a5ffdc1-262c-4017-8cf7-a281b2b2e945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>20c9237c-88c0-4a69-a212-cb1f9b8e844d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>91c7937f-f8bb-4515-8a0e-86b92d27a924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>aaa91d08-7b00-4571-b04b-bbeda84addbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bottomButtonRow&quot;)/input[@class=&quot;btn&quot;]</value>
      <webElementGuid>976fb7ba-ddc2-40fc-9546-a7fa8d00420f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_New Custom Object  Salesforce/iframe_New Custom Object_vfFrameId_1703668097612</value>
      <webElementGuid>a67de545-d6ac-4aaa-b041-28a26c9a2d74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='save'])[2]</value>
      <webElementGuid>8aa7ef36-a019-4ccc-8914-1094e27b9726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='bottomButtonRow']/input</value>
      <webElementGuid>f7d036ca-5220-47c5-b7a9-d06b5053f3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>362c49db-f5f4-40e3-82ac-1318574ae4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'save' and @title = 'Save' and @type = 'submit']</value>
      <webElementGuid>e10b64d6-7611-48c6-91a0-11406ca3de6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
