<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Demo</name>
   <tag></tag>
   <elementGuidId>f3e15a78-481b-4d1a-b22d-ba4635ca1f40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flexipage-tab2[@id='tab-4']/slot/flexipage-component2[2]/slot/lst-related-list-container/div/div/lst-related-list-single-container/laf-progressive-container/slot/lst-related-list-single-app-builder-mapper/article/lst-related-list-view-manager/lst-common-list-internal/div/div/lst-primary-display-manager/div/lst-primary-display/lst-primary-display-card/lst-customized-template-list/div/lst-template-list-item-factory/lst-related-preview-card/article/div/div/h3/lst-template-list-field/lst-output-lookup/force-lookup/div/records-hoverable-link/div/a/slot/slot/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#window</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6c1832f1-8dd7-4986-8eff-f02bace27f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-proxy-id</name>
      <type>Main</type>
      <value>aura-pos-lib-1</value>
      <webElementGuid>a52d954e-54e3-4270-8cd7-223cb48201ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>window</value>
      <webElementGuid>fc9bde69-53c5-489e-a9db-7260bd08c4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo</value>
      <webElementGuid>d02e9dd1-a0c6-4c4b-af17-8b78f24118de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;window&quot;)</value>
      <webElementGuid>645bef43-50fd-4615-b78a-1b3983c447cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flexipage-tab2[@id='tab-4']/slot/flexipage-component2[2]/slot/lst-related-list-container/div/div/lst-related-list-single-container/laf-progressive-container/slot/lst-related-list-single-app-builder-mapper/article/lst-related-list-view-manager/lst-common-list-internal/div/div/lst-primary-display-manager/div/lst-primary-display/lst-primary-display-card/lst-customized-template-list/div/lst-template-list-item-factory/lst-related-preview-card/article/div/div/h3/lst-template-list-field/lst-output-lookup/force-lookup/div/records-hoverable-link/div/a/slot/slot/span</value>
      <webElementGuid>83e94cc6-69f5-4988-aae4-01f86905c458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[2]/following::span[1]</value>
      <webElementGuid>4fcfe873-1196-429b-b548-0d5766cec99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1)'])[1]/following::span[1]</value>
      <webElementGuid>91a3495b-897e-4513-8464-a1e466c846e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Demo Preview'])[1]/preceding::span[1]</value>
      <webElementGuid>2208f525-5124-4474-b2e6-12d141c3ad22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title:'])[1]/preceding::span[2]</value>
      <webElementGuid>9e1891cb-1323-4b26-bc91-27c6bc6e3912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Demo']/parent::*</value>
      <webElementGuid>08794bb6-0824-4c89-9f91-af0aa186a268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lst-output-lookup/force-lookup/div/records-hoverable-link/div/a/slot/slot/span</value>
      <webElementGuid>7a996724-6b9f-4ea1-ad62-aca040516b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'window' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>60a56daa-b6e4-40b7-a5b4-e35ab56f0e9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
