<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Custom Object</name>
   <tag></tag>
   <elementGuidId>11fe251c-7557-4447-9c96-ee817a3693de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='createCustomObjectURL']/a/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slds-col.slds-size_10-of-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bed5b9e7-c2c1-46d2-b232-1d19a7ff9518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-col slds-size_10-of-12</value>
      <webElementGuid>b76eccd0-2240-43ef-917c-e82e1ed14a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>3075:0</value>
      <webElementGuid>e2f6759b-1016-4f99-97a5-535d28c2f906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Custom Object</value>
      <webElementGuid>67a75fb4-b247-405b-9707-993c1a82b161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createCustomObjectURL&quot;)/a[1]/div[@class=&quot;slds-grid&quot;]/div[@class=&quot;slds-col slds-size_10-of-12&quot;]</value>
      <webElementGuid>c2e24c4c-30ae-4d7a-9661-55cf5a554df0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='createCustomObjectURL']/a/div/div</value>
      <webElementGuid>46039d4a-0a3e-4762-bef8-76974b5e5243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[2]/following::div[4]</value>
      <webElementGuid>0689b924-05bf-49fd-b33e-4c2bc2b0d010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schema Builder'])[2]/following::div[9]</value>
      <webElementGuid>597987f5-7c47-4321-b389-5cc4391c8c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Object from Spreadsheet'])[1]/preceding::div[1]</value>
      <webElementGuid>7bd977ad-d586-4878-bf82-e1950f3efacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div</value>
      <webElementGuid>7ad81185-ab63-4edc-b711-2a353bcfb697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Custom Object' or . = 'Custom Object')]</value>
      <webElementGuid>27c35de1-41b6-41a5-998d-62b3dba027a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
