<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pricing</name>
   <tag></tag>
   <elementGuidId>23b75fd1-a3d8-4b43-86b9-9e9fc85d9e45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-640038 > a.menu-link > span.text-wrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-640038']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c6d5a5d-8263-42d8-bb48-0ea896b3c519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-wrap</value>
      <webElementGuid>ab1c10c1-a987-4685-b616-916494abb5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pricing</value>
      <webElementGuid>a8e42a61-ee31-4874-9edf-1ac1e11a1dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-640038&quot;)/a[@class=&quot;menu-link&quot;]/span[@class=&quot;text-wrap&quot;]</value>
      <webElementGuid>4c37e4f4-4804-4cc6-978d-7763389ad8f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-640038']/a/span</value>
      <webElementGuid>30813f1d-f787-4b65-8c95-8c3247a1d632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Royalty-free Images and Icons'])[1]/following::span[1]</value>
      <webElementGuid>19300f2e-8976-4093-b435-3f24fb9abcad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All Template Demos'])[1]/following::span[2]</value>
      <webElementGuid>aa5fe328-5daf-4b43-b7e6-20d37368181f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OceanWP Pro Bundle'])[1]/preceding::span[1]</value>
      <webElementGuid>33f1c978-009b-43fe-8e49-6c4708473740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ocean eCommerce Pro'])[1]/preceding::span[2]</value>
      <webElementGuid>f8557109-6cd6-4a12-80ae-4331897ab919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pricing']/parent::*</value>
      <webElementGuid>0a7db882-29a7-4b09-934f-b2b436348036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>4bd4a76d-b46a-457e-85cf-128a23b56405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pricing' or . = 'Pricing')]</value>
      <webElementGuid>03ed2477-9c2d-44ae-bbde-a05b5ae6d439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
