<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Name (2)</name>
   <tag></tag>
   <elementGuidId>13aa57af-2169-4b82-b3af-7788117a0d46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-233</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-233']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9060b48-fed1-42dc-8bad-ef0e906df99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>96599463-c619-4769-99f7-5943ad147c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-233</value>
      <webElementGuid>d6d6d71f-e2e5-42c7-b7ee-034acdc05216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-233</value>
      <webElementGuid>2e6ef444-8480-422b-8a10-b81699d88d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>22855d8e-2417-4d01-8c49-b612524590a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>c309d2e0-0797-46fe-a919-99b642786177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2fe2ce1-82de-4af9-83ae-b372b22f1141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c205c6d-0726-47ca-8299-859a24e860ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-233&quot;)</value>
      <webElementGuid>66c2c4f5-3a80-4540-a784-396e9beee467</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-233']</value>
      <webElementGuid>295e94d1-f412-446f-8852-c0d5fceb8f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-216']/div/slot/records-record-layout-row[2]/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>9d924f1a-7825-42e1-98e1-3291fa8e10f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-base-input/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>680a6c47-ac15-4ad5-9edf-bf2e1313d6ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-233' and @name = 'Name' and @type = 'text']</value>
      <webElementGuid>17783ef2-8021-42b9-b507-c8d4d9d1c1c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
