<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Frames_frame2</name>
   <tag></tag>
   <elementGuidId>6df74f75-dd14-40cd-a39e-7c0a7ff8c86b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frame2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='frame2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a0801a03-3a95-4724-9c69-cfdfdc957e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/sample</value>
      <webElementGuid>71487bcc-d42d-4c99-ad16-436d727ae893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame2</value>
      <webElementGuid>c5e9d067-d3fc-4ea7-acb3-f9321d3e4ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>6bdd31bb-ebcf-427c-a7e6-b73cb848fee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>a30ff46c-c5c1-426d-9762-5cf6863f4433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame2&quot;)</value>
      <webElementGuid>02b501a1-8ba5-46d8-a335-52365586196d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='frame2']</value>
      <webElementGuid>b1a4c94d-a295-4f09-9879-f5efa4eaae87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame2Wrapper']/iframe</value>
      <webElementGuid>e8dd3eaf-97d4-4d66-a9b4-5f5997f9aa78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/iframe</value>
      <webElementGuid>8c5436dc-4af6-487d-8c3b-cc629ba4c569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/sample' and @id = 'frame2']</value>
      <webElementGuid>ee01a858-bfd0-4838-9169-0619323eb28f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
