<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-base-combobox-item_Phone</name>
   <tag></tag>
   <elementGuidId>40696e00-5410-4d8f-bf82-bb1da3914748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-229-1-229</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-button-229-1-229']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-base-combobox-item</value>
      <webElementGuid>55781a8b-3d5a-423a-aecb-ee9d46955ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media slds-listbox__option slds-media_center slds-media_small slds-listbox__option_plain slds-has-focus</value>
      <webElementGuid>89765666-eedf-4508-b3af-59ad6f0a5c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-id</name>
      <type>Main</type>
      <value>combobox-button-229-1</value>
      <webElementGuid>ce72277c-c117-4178-8abd-10b975fc437d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>6da6382b-009a-4833-b733-21be8bf76ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8276d0bf-6348-4ad8-b611-52ed11759535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-button-229-1-229</value>
      <webElementGuid>8efb850f-078e-4dda-afec-5be28cc32b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>22c7be0c-b042-4476-b8f7-3e838a93e971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>649cd668-9db3-4995-90cf-7e42fe360253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>0d994fd2-a78a-4a70-85c2-8c82a46b2026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-229-1-229&quot;)</value>
      <webElementGuid>6ae54e03-2100-44d3-b318-218006648e34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-229-1-229']</value>
      <webElementGuid>51467fc4-0c39-4d28-a3b2-cf6ad9e1af83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown-element-229']/lightning-base-combobox-item[2]</value>
      <webElementGuid>ebf73b43-a797-4c0b-8aea-99c4288937aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[2]/following::lightning-base-combobox-item[1]</value>
      <webElementGuid>e597e442-7022-4ce8-986c-e4e1da0f34a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[1]/following::lightning-base-combobox-item[2]</value>
      <webElementGuid>762c4c89-6306-4bdb-a920-fbbe94d0643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::lightning-base-combobox-item[1]</value>
      <webElementGuid>188c52e8-a883-41d5-bb14-1ba6b78bbb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[2]</value>
      <webElementGuid>a4f545e3-942c-4fd2-a1bf-f203720cb282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id = 'combobox-button-229-1-229' and (text() = 'Phone' or . = 'Phone')]</value>
      <webElementGuid>4438827e-1a3d-4b3d-bdcc-3306607c1413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
