<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View profile_slds-r5</name>
   <tag></tag>
   <elementGuidId>ff0776c4-a917-452c-aa28-0be9a4579f7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.slds-r5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='453:83;a']/div/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bb7156da-9c39-4b25-8c13-4d7c455e74fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-r5</value>
      <webElementGuid>170b868b-1ade-4554-88b4-4b85679e5de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>441:83;a</value>
      <webElementGuid>d4ce4ddf-9664-43f2-8ee5-0600e4ca217a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;453:83;a&quot;)/div[@class=&quot;slds-icon-waffle&quot;]/div[@class=&quot;slds-r5&quot;]</value>
      <webElementGuid>434dc591-6f49-4c8d-92c3-7b4da657eb8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='453:83;a']/div/div[5]</value>
      <webElementGuid>05fd061e-587d-40fa-9588-3cd14d985e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div[5]</value>
      <webElementGuid>0d1912db-1374-4aae-8b2b-5ed54e096f56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
