<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View profile_slds-r2</name>
   <tag></tag>
   <elementGuidId>c71f90f0-c7a5-4039-82bf-681f40e7e8f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.slds-r2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='453:83;a']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb04d16e-659a-48e3-8253-ad106742f05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-r2</value>
      <webElementGuid>0f067f18-5562-432f-ae0a-f201d361278e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>438:83;a</value>
      <webElementGuid>a4286a11-5b9f-43fe-bda1-2c73b064445a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;453:83;a&quot;)/div[@class=&quot;slds-icon-waffle&quot;]/div[@class=&quot;slds-r2&quot;]</value>
      <webElementGuid>42995144-4dc6-4643-a959-303491eb0c02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='453:83;a']/div/div[2]</value>
      <webElementGuid>69795d5d-2b55-457c-874a-0f7d8fd99bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div[2]</value>
      <webElementGuid>71eca55a-9cca-4452-8292-5b66060668d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
