<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_Phone</name>
   <tag></tag>
   <elementGuidId>a5885a7a-bd87-4857-ba55-e32a8ea2692f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-187</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//slot/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95b8249d-69f9-4ba4-86ef-526d787dce77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>1b947597-f63a-4b3b-808a-03e2cb6275ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-187</value>
      <webElementGuid>d49792ab-e7f4-44dc-aeab-5ad71053a0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-187</value>
      <webElementGuid>385f75a8-71b4-477b-824f-0c6d2d4a3904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>df3095bf-0624-4343-aafb-7cca4fe1be74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>29c2bf30-71f0-4a38-b4be-3c89dd7eb370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9d77ab0-82fb-4c4b-bab1-43d67a1da8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e469882-1548-4b65-bfbe-d4ad4a9e1e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-187&quot;)</value>
      <webElementGuid>348b956d-42cd-4010-8b65-c8256349d6fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-167']/div/slot/records-record-layout-row[2]/slot/records-record-layout-item[2]/div/span/slot/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>e50dc438-f28b-44b8-bb67-e13f8b113aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//slot/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>f5a00bb1-330e-4730-b792-1be529a1be6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-187' or @name = 'Phone' and @type = 'text']</value>
      <webElementGuid>2b34fe9d-ef68-4e73-9906-ff8a2474a06a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
