<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-base-combobox-item_Installation Partner</name>
   <tag></tag>
   <elementGuidId>707c510a-0f89-4675-950c-c2ac133f0aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology Partner'])[1]/preceding::lightning-base-combobox-item[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-234-5-234</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-base-combobox-item</value>
      <webElementGuid>e6cd7a07-6a94-47b0-9f32-a7eead195057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media slds-listbox__option slds-media_center slds-media_small slds-listbox__option_plain slds-has-focus</value>
      <webElementGuid>7dea7eca-9562-44dd-99ab-9b60d25a04ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-id</name>
      <type>Main</type>
      <value>combobox-button-234-5</value>
      <webElementGuid>17186923-0a33-4770-933f-e53a9d36650a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Installation Partner</value>
      <webElementGuid>d8f20717-d8fd-4a63-be4d-6822c1095daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>268c937d-58be-4bc7-9012-0391c70fbcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-button-234-5-234</value>
      <webElementGuid>5ad63a3f-6887-466d-b6d7-973007d61c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>09182aac-eeaa-479f-bd8c-11c8ef09fd74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>78505d6e-d762-48d4-b1ca-352fb12465b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Installation Partner</value>
      <webElementGuid>304d3980-f9b0-4b00-9635-4b9ba767a95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-234-5-234&quot;)</value>
      <webElementGuid>975abbdd-6f71-411b-9bc9-c249e54b34dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-234-5-234']</value>
      <webElementGuid>5ee14cb5-c296-4fe5-bbc5-4ddd5e11cf0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown-element-234']/lightning-base-combobox-item[6]</value>
      <webElementGuid>e5dc9daf-b36a-4877-9970-e6fa247a6729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channel Partner / Reseller'])[1]/following::lightning-base-combobox-item[1]</value>
      <webElementGuid>c5bffc49-70de-4e38-bf56-7cf0241f3973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer - Channel'])[5]/following::lightning-base-combobox-item[2]</value>
      <webElementGuid>14ce99b0-f499-4ba7-a67c-6d4f01d7461a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology Partner'])[1]/preceding::lightning-base-combobox-item[1]</value>
      <webElementGuid>1f99bcf4-fc32-4d3d-933d-733a903c51f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[6]</value>
      <webElementGuid>0b8eb455-6c7e-4a60-a91c-930485cfcc6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id = 'combobox-button-234-5-234' and (text() = 'Installation Partner' or . = 'Installation Partner')]</value>
      <webElementGuid>c6589701-e326-44b5-b5b8-68747f9a6d1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
