<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_input-329</name>
   <tag></tag>
   <elementGuidId>335ee5a7-7b55-4c80-ac93-34dca59c9f1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-329</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-329']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a6cca722-b79d-4c93-9f7c-334bf7ac71dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-textarea</value>
      <webElementGuid>fc99d945-4905-4daa-ad58-4ff1b6858c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-329</value>
      <webElementGuid>69662037-98b4-4d72-ba81-a9c6b01545d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>textarea-label-329 null</value>
      <webElementGuid>d7cb89d9-1592-4166-ba1d-83fee68f2a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32000</value>
      <webElementGuid>872a2a2a-c647-425b-bdcd-11d78928f905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-329&quot;)</value>
      <webElementGuid>b5c7b04f-0abc-40e3-96eb-ddfad56292b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-329']</value>
      <webElementGuid>9107aa97-0439-4820-9e02-5958093bab45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-325']/div/slot/records-record-layout-row/slot/records-record-layout-item/div/span/slot/records-record-layout-text-area/lightning-textarea/div/textarea</value>
      <webElementGuid>e3dfd70f-de65-4964-a849-0c5064f6391e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::textarea[1]</value>
      <webElementGuid>bfbf5d2d-f89c-4c9e-b501-29c3ddac3480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description Information'])[1]/following::textarea[1]</value>
      <webElementGuid>3b733c55-5f5a-44a1-9f1a-9b3351542869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::textarea[1]</value>
      <webElementGuid>1a787c9e-c34a-4d88-ba01-ccf8924ea562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save &amp; New'])[1]/preceding::textarea[1]</value>
      <webElementGuid>e4da65b6-4b2b-48bf-822d-81bca5c49347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-text-area/lightning-textarea/div/textarea</value>
      <webElementGuid>a02c3d8c-6b88-4b4c-abc3-b10cb96ee2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-329']</value>
      <webElementGuid>05b465b9-acc7-405c-8c73-bff147d8f6a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
